module.exports = {
  language: [
    "swift",
    "objective-c",
    "shell",
    "python",
    "javascript",
    "java",
    "html",
    "c",
    "ruby",
    "php",
    "sql",
    "node",
    "css",
    "go"
  ],
  options: {
    "": "Best Match",
    stars: "Most Stars",
    forks: "Most Forks",
    updated: "Recently Updated"
  },
  pagination: {
    perPage: 30
  },
  tags: {
    algorithm: "Algorithm",
    atom: "Atom",
    android: "Android",
    angular: "Angular",
    aspnet: "ASP.NET",
    animation: "Animation",
    audio: "Audio",
    auto: "Browser automation",
    auth: "Authentication",
    autocomplete: "Autocomplete",
    bitcoin: "Bitcoin",
    bootstrap: "Bootstrap",
    bot: "Bot",
    babel: "Babel",
    book: "Book",
    build: "Building tool",
    "chrome-extension": "Chrome extension",
    compatibility: "Browser compatibility",
    clojure: "Clojure",
    crystal: "Crystal",
    "css-tool": "CSS Processor",
    "css-lib": "CSS Library",
    "css-in-js": "CSS in JS",
    chart: "Charts",
    compiler: "Compiler",
    django: "Django",
    docker: "Docker",
    dotnet: ".NET",
    d3: "D3",
    dom: "DOM manipulation",
    data: "Data fetching",
    "data-structure": "Data structure",
    db: "Database",
    date: "Date",
    dnd: "Drag and drop",
    electron: "Electron",
    email: "Email",
    express: "Express",
    ember: "Ember",
    es6: "Es6",
    eslint: "Eslint",
    firebase: "Firebase",
    flow: "Promises",
    fullstack: "Full-stack framework",
    fp: "Functional programming",
    game: "Game engine",
    graphql: "GraphQL",
    gulp: "Gulp",
    html: "HTML boilerplate",
    http: "HTTP client",
    ios: "iOS",
    ide: "IDE",
    icon: "Icons",
    image: "Image processing",
    iot: "IoT",
    json: "JSON",
    kotlin: "Kotlin",
    laravel: "Laravel",
    linux: "Linux",
    lint: "Linters",
    log: "Logging",
    "machine-learning": "Machine Learning",
    mongodb: "MongoDB",
    mysql: "MySQL",
    material: "Material design",
    meteor: "Meteor",
    module: "Module - bundler",
    "node.js": "Node.js core",
    "nodejs-framework": "Node.js framework",
    npm: "npm",
    notify: "Notification",
    "operating-system": "Operating system",
    offline: "Offline",
    package: "Package Dependency",
    performance: "Performance Optimization",
    process: "Process management",
    react: "React",
    rails: "Rails",
    "react-native": "React Native",
    redux: "Redux",
    r: "R",
    load: "Resource loader",
    routing: "Routing",
    sass: "Sass",
    scala: "Scala",
    security: "Security",
    svg: "SVG",
    sketch: "Sketch",
    symfony: "Symfony",
    scaffolding: "Scaffolding Generator",
    state: "State management",
    stream: "Stream",
    typescript: "TypeScript",
    table: "Table",
    template: "Templating",
    test: "Testing framework",
    tooltip: "Tooltip",
    framework: "UI Framework",
    ubuntu: "Ubuntu",
    unity: "Unity",
    util: "Utils",
    validation: "Validation",
    video: "Video",
    vue: "Vue",
    webpack: "Webpack",
    webworker: "Web workers",
    webgl: "WebGL",
    websocket: "Websocket"
  },
  token: "token 16eddd63fe6e79b0799208924a638d4891ed036d"
};
