
module.exports = {
  language: [
    "swift",
    "objective-c",
    "shell",
    "python",
    "javascript",
    "java",
    "html",
    "c",
    "ruby",
    "php",
    "sql",
    "node",
    "css",
    "go"
  ],
  options: {
    '' : 'Best Match',
    stars: 'Best Stars',
    forks: 'Best Forks',
    updated: 'Recently Updated'
  },
  pagination: {
    perPage: 30
  },
  tags: {
    angular: "Angular",
    animation: "Animation",
    audio: "Audio",
    auth: "Authentication",
    autocomplete: "Autocomplete",
    boilerplate: "Boilerplates",
    book: "Book",
    auto: "Browser automation",
    compatibility: "Browser compatibility",
    build: "Building tool",
    cms: "CMS",
    "css-tool": "CSS Processor",
    "css-lib": "CSS Library",
    "css-in-js": "CSS in JS",
    canvas: "Canvas",
    chart: "Charts",
    color: "Colors",
    compiler: "Compiler",
    component: "Component Toolkit",
    d3: "D3",
    dom: "DOM manipulation",
    dashboard: "Dashboard",
    data: "Data fetching",
    "data-structure": "Data structure",
    db: "Database",
    date: "Date",
    debug: "Debug",
    desktop: "Desktop app",
    dnd: "Drag and drop",
    drawing: "Drawing",
    email: "Email",
    express: "Express",
    flow : "Promises",
    fullstack: "Full-stack framework",
    fp: "Functional programming",
    game: "Game engine",
    graphql: "GraphQL",
    html: "HTML boilerplate",
    http: "HTTP client",
    ide: "IDE",
    icon: "Icons",
    image: "Image processing",
    iot: "IoT",
    json: "JSON",
    layout: "Layout",
    lint: "Linters",
    log: "Logging",
    ml: "Machine Learning",
    material: "Material design",
    math: "Math",
    meteor: "Meteor",
    mobile: "Mobile",
    module: "Module - bundler",
    "node.js": "Node.js core",
    "nodejs-framework": "Node.js framework",
    notify: "Notification",
    offline: "Offline",
    package: "Package Dependency",
    performance: "Performance Optimization",
    process: "Process management",
    react: "React",
    "react-native": "React Native",
    redux: "Redux",
    regexp: "Regular expression",
    load: "Resource loader",
    routing: "Routing",
    svg: "SVG",
    scaffolding: "Scaffolding Generator",
    state: "State management",
    stream: "Stream",
    table: "Table",
    template: "Templating",
    test: "Testing framework",
    tooltip: "Tooltip",
    framework: "UI Framework",
    util: "Utils",
    validation: "Validation",
    video: "Video",
    vue: "Vue",
    webworker: "Web workers",
    webgl: "WebGL",
    websocket: "Websocket"
  }
}
